#!/usr/bin/env bash
set -euo pipefail

log() {
  printf '[openclaw host egress pf] %s\n' "$*"
}

die() {
  printf '[openclaw host egress pf] error: %s\n' "$*" >&2
  exit 1
}

instance_primary_ip() {
  local name="$1"
  limactl shell "$name" -- bash -s <<'REMOTE' | tr -d '\r'
set -euo pipefail
ip route get 1.1.1.1 2>/dev/null |
  awk '{ for (i = 1; i <= NF; i++) if ($i == "src") { print $(i + 1); exit } }'
REMOTE
}

instance_default_gateway() {
  local name="$1"
  limactl shell "$name" -- bash -s <<'REMOTE' | tr -d '\r'
set -euo pipefail
ip route show default | awk '{ print $3; exit }'
REMOTE
}

ensure_pf_conf_anchor() {
  local anchor_name="$1"
  local anchor_file="$2"
  if sudo grep -qxF "anchor \"$anchor_name\"" /etc/pf.conf &&
    sudo grep -qxF "load anchor \"$anchor_name\" from \"$anchor_file\"" /etc/pf.conf; then
    return
  fi

  local backup="/etc/pf.conf.openclaw-bak-$(date +%Y%m%d%H%M%S)"
  log "backing up /etc/pf.conf to $backup"
  sudo cp /etc/pf.conf "$backup"
  {
    printf '\n# OpenClaw Lima untrusted egress guard\n'
    printf 'anchor "%s"\n' "$anchor_name"
    printf 'load anchor "%s" from "%s"\n' "$anchor_name" "$anchor_file"
  } | sudo tee -a /etc/pf.conf >/dev/null
}

main() {
  command -v limactl >/dev/null 2>&1 || die "limactl is required"
  command -v pfctl >/dev/null 2>&1 || die "pfctl is required"

  local gateway_instance="${OPENCLAW_GATEWAY_INSTANCE:-openclaw-gateway}"
  local untrusted_instance="${OPENCLAW_UNTRUSTED_INSTANCE:-openclaw-untrusted}"
  local proxy_port="${OPENCLAW_PIPELOCK_PORT:-8888}"
  [[ "$proxy_port" =~ ^[0-9]+$ ]] || die "OPENCLAW_PIPELOCK_PORT must be numeric"

  local dhcp_gateway gateway_ip untrusted_ip
  dhcp_gateway="$(instance_default_gateway "$untrusted_instance")"
  [[ -n "$dhcp_gateway" ]] || dhcp_gateway="255.255.255.255"
  gateway_ip="$(instance_primary_ip "$gateway_instance")"
  untrusted_ip="$(instance_primary_ip "$untrusted_instance")"
  [[ -n "$gateway_ip" ]] ||
    die "failed to resolve $gateway_instance primary egress IP; strict host egress needs a visible VZ NAT IP"
  [[ -n "$untrusted_ip" ]] ||
    die "failed to resolve $untrusted_instance primary egress IP; strict host egress needs a visible VZ NAT IP"
  [[ "$gateway_ip" != "$untrusted_ip" ]] ||
    die "$gateway_instance and $untrusted_instance resolved the same IP ($gateway_ip); strict host egress requires distinct VZ NAT addresses"

  local anchor_name="openclaw-lima-egress"
  local anchor_file="/etc/pf.anchors/$anchor_name"
  local tmp_anchor
  tmp_anchor="$(mktemp)"
  cat >"$tmp_anchor" <<PF
# Generated by OpenClaw Lima hardening.
# Untrusted may reach only the gateway Pipelock proxy. All other untrusted
# egress is dropped outside the guest.
openclaw_lima_gateway = "$dhcp_gateway"
openclaw_gateway = "$gateway_ip"
openclaw_untrusted = "$untrusted_ip"
openclaw_proxy_port = "$proxy_port"

pass quick proto udp from \$openclaw_untrusted port 68 to 255.255.255.255 port 67 keep state
pass quick proto udp from \$openclaw_untrusted port 68 to \$openclaw_lima_gateway port 67 keep state
pass quick proto tcp from \$openclaw_untrusted to \$openclaw_lima_gateway port \$openclaw_proxy_port keep state
block drop quick from \$openclaw_untrusted to any label "openclaw-untrusted-egress-block"
pass in quick proto tcp from 127.0.0.1 to any port \$openclaw_proxy_port keep state
pass in quick proto tcp from \$openclaw_untrusted to any port \$openclaw_proxy_port keep state
block drop in quick proto tcp from any to any port \$openclaw_proxy_port label "openclaw-pipelock-host-forward-block"
PF
  sudo install -m 0644 "$tmp_anchor" "$anchor_file"
  rm -f "$tmp_anchor"

  ensure_pf_conf_anchor "$anchor_name" "$anchor_file"
  log "validating PF config"
  sudo pfctl -nf /etc/pf.conf
  log "loading PF config"
  sudo pfctl -f /etc/pf.conf
  sudo pfctl -E >/dev/null 2>&1 || true

  log "active OpenClaw PF anchor"
  sudo pfctl -a "$anchor_name" -sr
}

main "$@"
