#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/claw-runtime-env.sh"
openclaw_prepare_runtime_dirs

log() {
  printf '[openclaw host egress pf] %s\n' "$*"
}

die() {
  printf '[openclaw host egress pf] error: %s\n' "$*" >&2
  exit 1
}

instance_primary_ip() {
  local name="$1"
  limactl shell "$name" -- bash -s <<'REMOTE' | tr -d '\r'
set -euo pipefail
ip route get 1.1.1.1 2>/dev/null |
  awk '{ for (i = 1; i <= NF; i++) if ($i == "src") { print $(i + 1); exit } }'
REMOTE
}

instance_default_gateway() {
  local name="$1"
  limactl shell "$name" -- bash -s <<'REMOTE' | tr -d '\r'
set -euo pipefail
ip route show default | awk '{ print $3; exit }'
REMOTE
}

ensure_pf_conf_anchor() {
  local anchor_name="$1"
  local anchor_file="$2"
  if sudo grep -qxF "anchor \"$anchor_name\"" /etc/pf.conf &&
    sudo grep -qxF "load anchor \"$anchor_name\" from \"$anchor_file\"" /etc/pf.conf; then
    return
  fi

  local backup="/etc/pf.conf.openclaw-bak-$(date +%Y%m%d%H%M%S)"
  log "backing up /etc/pf.conf to $backup"
  sudo cp /etc/pf.conf "$backup"
  {
    printf '\n# OpenClaw Lima untrusted egress guard\n'
    printf 'anchor "%s"\n' "$anchor_name"
    printf 'load anchor "%s" from "%s"\n' "$anchor_name" "$anchor_file"
  } | sudo tee -a /etc/pf.conf >/dev/null
}

main() {
  command -v limactl >/dev/null 2>&1 || die "limactl is required"
  command -v pfctl >/dev/null 2>&1 || die "pfctl is required"

  local gateway_instance="$OPENCLAW_GATEWAY_INSTANCE"
  local untrusted_instance="$OPENCLAW_UNTRUSTED_INSTANCE"
  local egress_target="${OPENCLAW_UNTRUSTED_EGRESS_TARGET:-pipelock}"
  local proxy_port="$OPENCLAW_PIPELOCK_PORT"
  local redirect_iface="${OPENCLAW_UNTRUSTED_EGRESS_IFACE:-bridge100}"
  local allowed_host allowed_port allowed_label
  case "$egress_target" in
    pipelock)
      allowed_port="$proxy_port"
      allowed_label="gateway Pipelock proxy"
      ;;
    locksmith)
      allowed_port="${OPENCLAW_LOCKSMITH_PORT:-9200}"
      allowed_label="host Locksmith"
      ;;
    *)
      die "OPENCLAW_UNTRUSTED_EGRESS_TARGET must be pipelock or locksmith"
      ;;
  esac
  [[ "$allowed_port" =~ ^[0-9]+$ ]] || die "allowed egress port must be numeric"
  [[ "$redirect_iface" =~ ^[A-Za-z0-9_.:-]+$ ]] || die "OPENCLAW_UNTRUSTED_EGRESS_IFACE is not a valid PF interface name"

  local dhcp_gateway gateway_ip untrusted_ip
  dhcp_gateway="$(instance_default_gateway "$untrusted_instance")"
  [[ -n "$dhcp_gateway" ]] || dhcp_gateway="255.255.255.255"
  if [[ "$egress_target" == "pipelock" ]]; then
    gateway_ip="$(instance_primary_ip "$gateway_instance")"
  else
    gateway_ip=""
  fi
  untrusted_ip="$(instance_primary_ip "$untrusted_instance")"
  if [[ "$egress_target" == "pipelock" ]]; then
    [[ -n "$gateway_ip" ]] ||
      die "failed to resolve $gateway_instance primary egress IP; strict host egress needs a visible VZ NAT IP"
  fi
  [[ -n "$untrusted_ip" ]] ||
    die "failed to resolve $untrusted_instance primary egress IP; strict host egress needs a visible VZ NAT IP"
  if [[ "$egress_target" == "pipelock" ]]; then
    [[ "$gateway_ip" != "$untrusted_ip" ]] ||
      die "$gateway_instance and $untrusted_instance resolved the same IP ($gateway_ip); strict host egress requires distinct VZ NAT addresses"
  fi
  allowed_host="${OPENCLAW_UNTRUSTED_EGRESS_HOST:-$dhcp_gateway}"

  local anchor_name="$OPENCLAW_PF_ANCHOR_NAME"
  local anchor_file="/etc/pf.anchors/$anchor_name"

  # Another runtime's anchor claiming the same proxy port ends in a
  # "block drop in ... port <proxy_port>" that fires before this anchor and
  # silently drops this runtime's untrusted->Pipelock traffic. Fail loudly
  # instead; stale anchors from stopped runtimes are still loaded by PF.
  local other_anchor
  if [[ "$egress_target" == "pipelock" ]]; then
    for other_anchor in /etc/pf.anchors/*openclaw-lima-egress*; do
      [[ -f "$other_anchor" && "$other_anchor" != "$anchor_file" ]] || continue
      if grep -q "^openclaw_proxy_port = \"$proxy_port\"$" "$other_anchor"; then
        die "PF anchor $(basename "$other_anchor") already claims Pipelock port $proxy_port. Use a different OPENCLAW_RUNTIME_PORT_OFFSET, or remove the stale anchor (sudo pfctl -a '$(basename "$other_anchor")' -F rules; sudo rm '$other_anchor' and its /etc/pf.conf lines) if that runtime is gone."
      fi
    done
  fi

  local tmp_anchor
  tmp_anchor="$(mktemp)"
  cat >"$tmp_anchor" <<PF
# Generated by OpenClaw Lima hardening.
# Untrusted may reach only the configured $allowed_label. All other untrusted
# egress is dropped outside the guest.
openclaw_lima_gateway = "$dhcp_gateway"
openclaw_untrusted = "$untrusted_ip"
openclaw_allowed_host = "$allowed_host"
openclaw_allowed_port = "$allowed_port"

PF
  if [[ "$egress_target" == "locksmith" ]]; then
    cat >>"$tmp_anchor" <<PF
rdr pass on $redirect_iface inet proto tcp from \$openclaw_untrusted to \$openclaw_allowed_host port \$openclaw_allowed_port -> 127.0.0.1 port \$openclaw_allowed_port

PF
  fi
  cat >>"$tmp_anchor" <<'PF'
pass quick proto udp from $openclaw_untrusted port 68 to 255.255.255.255 port 67 keep state
pass quick proto udp from $openclaw_untrusted port 68 to $openclaw_lima_gateway port 67 keep state
pass quick proto tcp from $openclaw_untrusted to $openclaw_allowed_host port $openclaw_allowed_port keep state
block drop quick from $openclaw_untrusted to any label "openclaw-untrusted-egress-block"
PF
  if [[ "$egress_target" == "pipelock" ]]; then
    cat >>"$tmp_anchor" <<'PF'
pass in quick proto tcp from 127.0.0.1 to any port $openclaw_allowed_port keep state
pass in quick proto tcp from $openclaw_untrusted to any port $openclaw_allowed_port keep state
block drop in quick proto tcp from any to any port $openclaw_allowed_port label "openclaw-pipelock-host-forward-block"
PF
  fi
  sudo install -m 0644 "$tmp_anchor" "$anchor_file"
  rm -f "$tmp_anchor"

  ensure_pf_conf_anchor "$anchor_name" "$anchor_file"
  log "validating PF config"
  sudo pfctl -nf /etc/pf.conf
  log "loading PF config"
  sudo pfctl -f /etc/pf.conf
  sudo pfctl -E >/dev/null 2>&1 || true

  log "active OpenClaw PF anchor"
  sudo pfctl -a "$anchor_name" -sr
}

main "$@"
